### ISSUE TITLE
Lossless webp?

### ISSUE THREAD

**Issue by rdinnager** [jeroen/webp#4]
Correct me if I am mistaken, but it looks from the source code that this package currently only supports lossy webp images for writing. Is there any plans to implement writing lossless? If not, it should perhaps be made clear in the Readme that only lossy is supported for `write_webp()`. I personally would like to see lossless support. I would be willing to try a PR myself if would help (my C skills are limited but it looks pretty straightforward to base off lossy functions since the lossless functions have identical arguments, except without quality_factor: https://raw.githubusercontent.com/webmproject/libwebp/36a6eea3bc2871c7f0166193a6fa42241af4a464/src/webp/encode.h).

**Comment by jeroen** [comment]
I had assumed that setting quality to 100 effectively meant lossless, but maybe you are right and we need to use another api to get lossless output.

**Comment by rdinnager** [comment]
Thanks for adding this in!
